source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'

gem 'opal', github: 'youchan/opal', branch: 'marshal-dump-bignum'
gem 'opal-sprockets', github: 'opal/opal-sprockets'
gem 'hyalite'
gem 'opal-drb'

gem 'rake'
gem 'sqlite3'

gem 'haml'
gem 'sass'
