eval$s=%w(
  s=%(eval$s=%w(#{$s})*"");

  d = 
"BAhbLCIdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIh0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIh0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIdAAAAAAAAH4AAAAAAAAAAAAAB8AAAAHwAIh0H/8AAAAAfgAAAAAH4B/AAAAPwAAAA/AAiHQf/8AAAAB+AAAAAAfgP4AAAA/AAAAD8ACIdB//4AAAAH4AAAAAB+D/AAAAD8AAAAPwAIh0H//wAAAAfAAAAAAH4f4AAAALAAAAAkAAiHQ/r/AAAAB8AAAAAA/D/AAAAAAAAAAAAACIdD8D8H4H4Px8B8Afj8fwAX+AH4A+PwfgAIh0PwPwfgfg/f8H4D8Pz+AH/+AfgP+/B+AAiHQ/A/D8B8D//wPgPw//wAf/8B+B//4HwACIdD8H4HwPwP//g+B+H/+AB//wHwP//gfAAIh0fg/g/A/A/x+D4Hwf/gAEA/AfB/H+B8AAiHR//8D8D8H8H8Pw/B/8AAAB+D8H4P4PwACIdH//APwPwfgPgfD4H/wAAf/4Pw/Afg/AAIh0f/4A+A+B+A/B8fgf/gAH//A/D8D8D8AAiHR//wD4D4HwD8Hx8B/+AB//8D4PgHwPgACIdP4/gfgfgfAPgfPwP38AH9vwfh+A/A+AAIh0/B+B+B+D8B+B8+A/P4A/A/A+H4D8H4AAiHT8D8H4H4PwH4D/4D8fwD4D8H4fgPwfgACIdPwPwfg/g/g/AP/APw/gPgfgfh+B/B+AAIh1/A/B+H8D+P8A/4B/B/B/D+B8H+P4HwAAiHX4B+H//wP//gB/gH4H8D//4HwP//gfAACIdfgH4f//A//8AH8AfgP4P//g/Af/+D8AAIh1+Afh/74H7/gAfwB+Afwf5+D8B/34PwAAiHX4B+B+Pwfn4AB+AH4A/g/HwPwB8fA/AACIdAAAAAAAAAAAAHwAAAAAAAAAAAAD8AAAAIh0AAAAAAAAAAAAfAAAAAAAAAAAAAPwAAAAiHQAAAAAAAAAAAD4AAAAAAAAAAAYD+AAAACIdAAAAAAAAAAAD/gAAAAAAAAAAB//wAAAAIh0AAAAAAAAAAAf8AAAAAAAAAAAH/+AAAAAiHQAAAAAAAAAAB/gAAAAAAAAAAAf/wAAAACIdAAAAAAAAAAAH4AAAAAAAAAAAA/4AAAAAIh0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

  index = 0;
  f = -> n { b=s.slice(index, n); index += 1; b };

  require('base64');

  ARGV[0] != 'server' && proc {
    Marshal.load(Base64.decode64(d)).each {|line|
      line.chars.each {|char|
        byte = char.bytes[0];
        8.times {|i|
          print((byte & (1 << (7 - i))) > 0 ? f[1] : "\s");
        }
      };
      puts
    }
  }.call;

  ARGV[0] == 'server' && proc{
    require('drb/drb');
    r = -> { s };

    DRb.start_service("ws://127.0.0.1:1234", r);
    DRb.thread.join
  }.call;

  "RubyKaigi\s2017\sSep.18th-20th\sInternational\sConference\sCenter\sHiroshima,\sHiroshima,\sJapan";
)*""
